[package]
name = "msf-stun"
version = "0.1.2"
authors = ["Ondrej Perutka <perutka.ondrej@gmail.com>"]
edition = "2021"
readme = "README.md"
license = "MIT"
documentation = "https://docs.rs/msf-stun/"
repository = "https://github.com/operutka/msf"
description = """
Session Traversal Utilities for NAT (STUN) for Rust.
"""
keywords = ["protocol", "network"]

[features]
default = []
turn = []
ice = []

[dependencies]
bytes = "1"
crc = "3"
hmac = "0.13"
sha1 = "0.11"
sha2 = "0.11"

[dependencies.zerocopy]
version = "0.8"
features = ["derive"]
