[package]
name = "msf-ice"
version = "0.2.4"
authors = ["Ondrej Perutka <perutka.ondrej@gmail.com>"]
edition = "2021"
readme = "README.md"
license = "MIT"
documentation = "https://docs.rs/msf-ice/"
repository = "https://github.com/operutka/msf"
description = """
Interactive Connectivity Establishment (ICE) for Rust.
"""
keywords = ["async", "protocol", "network"]

[dependencies]
bytes = "1"
futures = "0.3"
md5 = "0.8"
rand = "0.10"
trait-variant = "0.1"

[dependencies.log]
version = "0.4"
optional = true

[dependencies.msf-stun]
version = "0.2"
features = ["ice", "turn"]
path = "../msf-stun"

[dependencies.slog]
version = "2"
optional = true

[dependencies.tokio]
version = "1"
features = ["io-util", "net", "rt", "time"]

[dependencies.zerocopy]
version = "0.8"
features = ["derive"]
